title:              ELMS:LN Project Home

# Versioning
current_version: 1.5.0
foundation_version: 6.0.0

author:
  name:             username
  email:            user@domain.com
  github:           username
  twitter:          username

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
# source:             ./source Git Pages overrides this variable
# destination:        ./static

port:               9002
url: http://www.elmsln.org # the base hostname & protocol for your site
baseurl: ""

# exclude this stuff when building the static site
exclude:            [
                      '.gitignore',
                      'README.md',
                      'Gemfile',
                      'Gemfile.lock',
                    ]

## CUSTOM VARS


#ga_id:             ##-########-###
site_name:          ELMS:LN
site_description :  
site_copyright:     Copyright (c) 2017
site_url:           http://www.elmsln.org
site_email:         
site_phone:         



# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/stylesheets
  style:            :compressed

# Collections 
collections:
  courses:
  team:
 #  _   _     __      _______ _____       _______ _____ ____  _   _ 
 # | \ | |   /\ \    / /_   _/ ____|   /w\|__   __|_   _/ __ \| \ | |
 # |  \| |  /  \ \  / /  | || |  __   /  \  | |    | || |  | |  \| |
 # | . ` | / /\ \ \/ /   | || | |_ | / /\ \ | |    | || |  | | . ` |
 # | |\  |/ ____ \  /   _| || |__| |/ ____ \| |   _| || |__| | |\  |
 # |_| \_/_/    \_\/   |_____\_____/_/    \_\_|  |_____\____/|_| \_|

#Navigation
menuitems:
  - url: /
    title: Home
  - url: /about/
    title: About
  - url: /examples/
    title: Examples
  - url: /documentation/
    title: Documentation
  - url: /blog/
    title: Blog
