url: elmsln.org # the base hostname & protocol for your site
baseurl: ""

#ga_id:             ##-########-###
site_name:          ELMS:LN Project Home
site_description :  The new homepage for ELMS:LN
site_copyright:     Copyright (c) 2017
site_url:           elmsln.org
site_email:         dmd@psu.edu
site_phone:         

#Navigation
menuitems:
  - url: 
    title: Home
  - url: /program/
    title: Program
  - url: /about/
    title: About